### ISSUE TITLE
Cant copy or paste selected line or word

### ISSUE THREAD

**Issue by MuhtasimMahim** [mHamzaHanif/Text-Editor-Python#1]
You can add a new function which allows selected line or letter to copy or paste by using right click.
By the way CTRL+C and CTRL+V works

**Comment by mHamzaArain** [comment]
Yeah you can send me pull request after adding additional features

**Comment by mHamzaArain** [comment]
You can check this project based on pyqt5 more easier than tkinter
https://github.com/mHamzaHanif/Library-Management-System
